name: Package TOMLs into JSON

on:
  workflow_call:

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: marceloprado/has-changed-path@v1.0.1
        id: schema-changed
        with:
          paths: ./schemas

      - name: Wait for JSON schema to generate
        uses: lewagon/wait-on-check-action@v1.3.1
        if: ${{ steps.schema-changed.outputs.changed }}
        with:
          ref: ${{ github.ref }}
          check-name: "Generate JSON Schemas"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 5

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip install tomlkit check-jsonschema

      - name: Generate raw data file
        run: python .github/workflows/package_data.py ${{ github.sha }}

      - name: Validate generated file
        run: npx ajv-cli -s ./schemas/generated/data.json --errors=text -d ./raw/data.json

      - name: Commit schemas
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated data.json for ${{ github.sha }}"
